In [2]:
# Cell 1: Environment Diagnostics and Dependency Verification
import numpy as np
import pandas as pd
import sys

print(f"== WORKSTATION SYSTEM HEALTH CHECK ==")
print(f"Python Environment: {sys.version}")
print(f"NumPy Version Live: {np.__version__}")
print(f"Pandas Version Live: {pd.__version__}")
print(f"Status: Diagnostic Complete. Workspace Ready.")

== WORKSTATION SYSTEM HEALTH CHECK ==
Python Environment: 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]
NumPy Version Live: 2.4.4
Pandas Version Live: 3.0.2
Status: Diagnostic Complete. Workspace Ready.

In [3]:
# Cell 2: Raw Operational Data Simulation
# Creating a dictionary with intentional formatting discrepancies and missing values

raw_log_data = {
    'Transaction_Timestamp': ['2026-07-09 08:30:00', '2026-07-09 09:15:00', None, '2026-07-09 11:45:00', '2026-07-09 14:20:00'],
    'Territory_ID': ['PAT-01', 'PAT-02', 'PAT-01', 'PAT-03', 'PAT-02'],
    'Operational_Value': [12500.0, None, 14200.0, 9800.0, 15500.0],
    'Log_Status': [' SUCCESS ', ' PENDING ', ' SUCCESS', 'FAILED', ' SUCCESS ']
}

# Convert the dictionary into an enterprise Pandas DataFrame
df_log = pd.DataFrame(raw_log_data)

print("== STEP 3: PIPELINE INGESTION COMPLETE ==")
df_log

== STEP 3: PIPELINE INGESTION COMPLETE ==

  Transaction_Timestamp Territory_ID  Operational_Value Log_Status
0   2026-07-09 08:30:00       PAT-01            12500.0   SUCCESS
1   2026-07-09 09:15:00       PAT-02                NaN   PENDING
2                   NaN       PAT-01            14200.0    SUCCESS
3   2026-07-09 11:45:00       PAT-03             9800.0     FAILED
4   2026-07-09 14:20:00       PAT-02            15500.0   SUCCESS

In [4]:
# Cell 3: Column Vector String Cleansing
# Stripping whitespace from text boundaries to ensure exact string matching

print("== BEFORE SANITIZATION (Raw String Lengths) ==")
print(df_log['Log_Status'].tolist())

# Apply the string strip transformation directly to the vector
df_log['Log_Status'] = df_log['Log_Status'].str.strip()

print("\n== AFTER SANITIZATION (Sanitized String Lengths) ==")
print(df_log['Log_Status'].tolist())

== BEFORE SANITIZATION (Raw String Lengths) ==
[' SUCCESS ', ' PENDING ', ' SUCCESS', 'FAILED', ' SUCCESS ']

== AFTER SANITIZATION (Sanitized String Lengths) ==
['SUCCESS', 'PENDING', 'SUCCESS', 'FAILED', 'SUCCESS']

In [5]:
# Cell 3: Column Vector String Cleansing
# Stripping whitespace from text boundaries to ensure exact string matching

print("== BEFORE SANITIZATION (Raw String Lengths) ==")
print(df_log['Log_Status'].tolist())

# Apply the string strip transformation directly to the vector
df_log['Log_Status'] = df_log['Log_Status'].str.strip()

print("\n== AFTER SANITIZATION (Sanitized String Lengths) ==")
print(df_log['Log_Status'].tolist())

== BEFORE SANITIZATION (Raw String Lengths) ==
['SUCCESS', 'PENDING', 'SUCCESS', 'FAILED', 'SUCCESS']

== AFTER SANITIZATION (Sanitized String Lengths) ==
['SUCCESS', 'PENDING', 'SUCCESS', 'FAILED', 'SUCCESS']

In [6]:
# Cell 4: Statistical Imputation of Missing Numeric Variables
# Calculating the median of the column and using it to fill missing data points

# Calculate the median value (ignoring NaN elements)
median_value = df_log['Operational_Value'].median()
print(f"Calculated Operational Column Median: {median_value}")

# Fill the missing values using .fillna()
df_log['Operational_Value'] = df_log['Operational_Value'].fillna(median_value)

print("\n== STEP 5: IMPUTATION COMPLETE ==")
df_log

Calculated Operational Column Median: 13350.0

== STEP 5: IMPUTATION COMPLETE ==

  Transaction_Timestamp Territory_ID  Operational_Value Log_Status
0   2026-07-09 08:30:00       PAT-01            12500.0    SUCCESS
1   2026-07-09 09:15:00       PAT-02            13350.0    PENDING
2                   NaN       PAT-01            14200.0    SUCCESS
3   2026-07-09 11:45:00       PAT-03             9800.0     FAILED
4   2026-07-09 14:20:00       PAT-02            15500.0    SUCCESS

In [7]:
# Cell 5: Operational Group Aggregations
# Grouping by final log states to extract business metrics and cumulative sums

print("== STEP 6: EXECUTING METRIC EXTRACTION ==")

# Calculate sum and mean simultaneously using descriptive aggregations
performance_metrics = df_log.groupby('Log_Status')['Operational_Value'].agg(['count', 'sum', 'mean']).round(2)

print("\n== FINAL OPERATIONAL METRICS FOR EXECUTIVE REPORTING ==")
print(performance_metrics)

== STEP 6: EXECUTING METRIC EXTRACTION ==

== FINAL OPERATIONAL METRICS FOR EXECUTIVE REPORTING ==
            count      sum      mean
Log_Status
FAILED          1   9800.0   9800.00
PENDING         1  13350.0  13350.00
SUCCESS         3  42200.0  14066.67

In [7]:
# Cell 6: Direct Ingestion from Local Storage Pipelines
import io

# Simulating a raw local CSV file structure for operational training
csv_storage_mock = """Transaction_ID,Region,Metric_Score
TXN101,East,88.5
TXN102,West,92.0
TXN103,East,NaN
TXN104,North,79.1
TXN105,South,84.6
"""

# In production, this would be: df_csv = pd.read_csv('flight-delays-project/flights.csv')
df_csv = pd.read_csv(io.StringIO(csv_storage_mock))

print("== STEP 7: EXTERNAL FILE DISK INGESTION SUCCESSFUL ==")
df_csv

== STEP 7: EXTERNAL FILE DISK INGESTION SUCCESSFUL ==

  Transaction_ID Region  Metric_Score
0         TXN101   East          88.5
1         TXN102   West          92.0
2         TXN103   East           NaN
3         TXN104  North          79.1
4         TXN105  South          84.6

In [8]:
# Cell 7: Conditional Location Filtering and Targeted Modification
# Using .loc to isolate specific regions and update missing target parameters

print("== STEP 8: RUNNING CONDITIONAL AUDIT ==")

# Let's find rows where the Region is 'East'
east_region_mask = df_csv['Region'] == 'East'

print("\n== BEFORE TARGETED FIX (Isolating East Region) ==")
print(df_csv.loc[east_region_mask])

# Replace the NaN score specifically for the East region with a baseline score of 85.0
df_csv.loc[east_region_mask & (df_csv['Metric_Score'].isna()), 'Metric_Score'] = 85.0

print("\n== AFTER TARGETED FIX (Missing East Score Resolved) ==")
df_csv

== STEP 8: RUNNING CONDITIONAL AUDIT ==

== BEFORE TARGETED FIX (Isolating East Region) ==
  Transaction_ID Region  Metric_Score
0         TXN101   East          88.5
2         TXN103   East           NaN

== AFTER TARGETED FIX (Missing East Score Resolved) ==

  Transaction_ID Region  Metric_Score
0         TXN101   East          88.5
1         TXN102   West          92.0
2         TXN103   East          85.0
3         TXN104  North          79.1
4         TXN105  South          84.6

In [9]:
# Cell 8: Enterprise File Export Operations
# Writing the clean, processed dataframe out to a physical disk file

print("== STEP 9: INITIATING SYSTEM DISK EXPORT ==")

# Define the target export file name
export_filename = "sanitized_operational_metrics.csv"

# Write the data to a physical CSV file on your machine
# index=False ensures we don't save the row index numbers (0, 1, 2) inside the file
df_csv.to_csv(export_filename, index=False)

print(f"\nSUCCESS: Clean dataset compiled and saved directly as: '{export_filename}'")
print("Check your local workspace directory—the file is officially live.")

== STEP 9: INITIATING SYSTEM DISK EXPORT ==

SUCCESS: Clean dataset compiled and saved directly as: 'sanitized_operational_metrics.csv'
Check your local workspace directory—the file is officially live.

In [10]:
# Cell 9: Post-Loading Integrity Validation Check
# Verifying the file written to disk can be parsed cleanly by database engines

print("== STEP 10: INITIATING DATA INTEGRITY CHECK ==")

# Read the newly generated physical file from disk
df_verification = pd.read_csv("sanitized_operational_metrics.csv")

print("\n== DATA VERIFICATION COMPLETION ==")
print(f"Total Columns Verified: {list(df_verification.columns)}")
print(f"Total Rows Verified: {len(df_verification)}")
print("\nFinal Verified Dataset:")
df_verification

== STEP 10: INITIATING DATA INTEGRITY CHECK ==

== DATA VERIFICATION COMPLETION ==
Total Columns Verified: ['Transaction_ID', 'Region', 'Metric_Score']
Total Rows Verified: 5

Final Verified Dataset:

  Transaction_ID Region  Metric_Score
0         TXN101   East          88.5
1         TXN102   West          92.0
2         TXN103   East          85.0
3         TXN104  North          79.1
4         TXN105  South          84.6

In [1]:
# Cell 10: Logistics High-Volume DateTime Ingestion Pipeline
import pandas as pd
import io

# Simulating a raw flight-delays logistics data stream with missing intervals and string variations
logistics_raw_data = """Carrier,Flight_Num,Scheduled_Departure,Actual_Departure,Delay_Reason
Indigo,IND-402,2026-07-10 13:00:00,2026-07-10 13:15:00,Weather
AirIndia,AI-182,2026-07-10 14:30:00,None,Gate Delay
SpiceJet,SG-901,2026-07-10 15:00:00,2026-07-10 15:00:00,None
Indigo,IND-211,2026-07-10 18:45:00,2026-07-10 19:22:00,Carrier Delay
AirIndia,AI-884,2026-07-10 21:00:00,2026-07-10 21:05:00,None
"""

# Load dataset and explicitly force Pandas to recognize structural components
df_logistics = pd.read_csv(io.StringIO(logistics_raw_data))

print("== LOGISTICS FLIGHT DATASTREAM INGESTED ==")
df_logistics

== LOGISTICS FLIGHT DATASTREAM INGESTED ==

,Carrier,Flight_Num,Scheduled_Departure,Actual_Departure,Delay_Reason
0,Indigo,IND-402,2026-07-10 13:00:00,2026-07-10 13:15:00,Weather
1,AirIndia,AI-182,2026-07-10 14:30:00,NaN,Gate Delay
2,SpiceJet,SG-901,2026-07-10 15:00:00,2026-07-10 15:00:00,NaN
3,Indigo,IND-211,2026-07-10 18:45:00,2026-07-10 19:22:00,Carrier Delay
4,AirIndia,AI-884,2026-07-10 21:00:00,2026-07-10 21:05:00,NaN

In [2]:
# Cell 11: Vectorized Datetime Transformations and Metric Derivation
# Converting text series to datetime objects and extracting exact operational delay differentials

print("== STEP 11: RUNNING OPERATIONAL DATETIME MATH ==")

# 1. Convert text strings into formal Pandas Datetime objects
df_logistics['Scheduled_Departure'] = pd.to_datetime(df_logistics['Scheduled_Departure'])
df_logistics['Actual_Departure'] = pd.to_datetime(df_logistics['Actual_Departure'])

# 2. Calculate the exact delta in minutes using vectorized subtraction
# .dt.total_seconds() / 60 isolates the exact floating-point minute variance
df_logistics['Delay_Minutes'] = (df_logistics['Actual_Departure'] - df_logistics['Scheduled_Departure']).dt.total_seconds() / 60

# 3. For flights that never departed (NaN), handle the missing delta cleanly by defaulting to 0.0 for calculations
df_logistics['Delay_Minutes'] = df_logistics['Delay_Minutes'].fillna(0.0)

print("\n== LOGISTICS TIMELINE TRANSFORMATIONS COMPLETE ==")
df_logistics[['Carrier', 'Flight_Num', 'Scheduled_Departure', 'Actual_Departure', 'Delay_Minutes', 'Delay_Reason']]

== STEP 11: RUNNING OPERATIONAL DATETIME MATH ==

== LOGISTICS TIMELINE TRANSFORMATIONS COMPLETE ==

,Carrier,Flight_Num,Scheduled_Departure,Actual_Departure,Delay_Minutes,Delay_Reason
0,Indigo,IND-402,2026-07-10 13:00:00,2026-07-10 13:15:00,15.0,Weather
1,AirIndia,AI-182,2026-07-10 14:30:00,NaT,0.0,Gate Delay
2,SpiceJet,SG-901,2026-07-10 15:00:00,2026-07-10 15:00:00,0.0,NaN
3,Indigo,IND-211,2026-07-10 18:45:00,2026-07-10 19:22:00,37.0,Carrier Delay
4,AirIndia,AI-884,2026-07-10 21:00:00,2026-07-10 21:05:00,5.0,NaN

In [3]:
# Cell 12: Multi-Variable Carrier Performance Metrics
# Aggregating logistics volume and calculating metrics for operational reporting

print("== STEP 12: COMPILING CARRIER SCORECARD ==")

# Group by Carrier to isolate total flight counts, maximum delays, and sum of total delay minutes
carrier_scorecard = df_logistics.groupby('Carrier')['Delay_Minutes'].agg(
    Total_Flights='count',
    Max_Delay_Minutes='max',
    Total_Delay_Minutes='sum'
).reset_index()

print("\n== EXECUTIVE LOGISTICS REPORT ==")
carrier_scorecard

== STEP 12: COMPILING CARRIER SCORECARD ==

== EXECUTIVE LOGISTICS REPORT ==

    Carrier  Total_Flights  Max_Delay_Minutes  Total_Delay_Minutes
0  AirIndia              2                5.0                  5.0
1    Indigo              2               37.0                 52.0
2  SpiceJet              1                0.0                  0.0

In [4]:
# Cell 13: Staging Core Aggregations to Disk Storage
# Exporting the clean carrier analytics matrix for downstream database ingestion

print("== STEP 13: EXPORTING LOGISTICS METRICS TO DISK ==")

# Define our target destination file name
logistics_export_file = "carrier_performance_scorecard.csv"

# Write out the aggregated dataframe to a physical CSV file
carrier_scorecard.to_csv(logistics_export_file, index=False)

print(f"\nSUCCESS: Operational report successfully compiled and saved as: '{logistics_export_file}'")
print("Your local file repository is now updated with this live report.")

== STEP 13: EXPORTING LOGISTICS METRICS TO DISK ==

SUCCESS: Operational report successfully compiled and saved as: 'carrier_performance_scorecard.csv'
Your local file repository is now updated with this live report.